// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    let s1 = s.toString().split('').sort();
    s1.push('0');
    let s2 = t.toString().split('').sort();
    for (let i = 0; i < s1.length; i++) {
        if (s1[i] != s2[i]) return s2[i];
    }
};