// You are given three positive integers num1, num2, and num3.
// The key of num1, num2, and num3 is defined as a four-digit number such that:
// - Initially, if any number has less than four digits, it is padded with leading zeros.
// - The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
// Return the key of the three numbers without leading zeros (if any).

/**
 * @param {number} num1
 * @param {number} num2
 * @param {number} num3
 * @return {number}
 */
var generateKey = function (num1, num2, num3) {
    return +(new Array(4).fill(false).reduce((acc, cur, cdx) => {
        acc.ret += Math.min.apply(null, acc.arr.map(s => +s[cdx]));
        return acc;
    }, { ret: '', arr: Array.from(arguments).map(n => n.toString().padStart(4, 0)) }).ret);
};